### ISSUE TITLE
Maybe more WinUI 3?

### ISSUE THREAD

**Issue by pdimu** [wherewhere/Text-Reader#12]
### Describe your feature request

it'd be amazing if we would look at our texts and say: 'Wow, it's so fluent!'. That's why we have WinUI 3

### How important is this to you?

Nice-to-have

### Describe the solution you'd like

we can learn more at: [MS Learn App dev for WinUI 3](https://learn.microsoft.com/en-us/windows/apps/winui/winui3/)
and also explore the WinUI 3 Gallery in its dedicated app: [MS Store app for WinUI 3 Gallery](https://www.microsoft.com/store/productId/9P3JFPWWDZRC?ocid=pdpshare)

### Describe alternatives you've considered

i really do not recommend trying to do a WinUI 3-looking app, because these are really scratchy and community don't like them. so please consider my solution (the app developing part is at the MS Learn link)

**Comment by wherewhere** [comment]
No! Go away!

**Comment by okgamr** [comment]
ok, don't be mad, i was just asking
