### ISSUE TITLE
Remove space between each chinses word 移除中文字符之间的空格

### ISSUE THREAD

**Issue by MineClever** [wherewhere/Text-Reader#7]
### Describe your feature request

Remove space between each chinses word
移除中文字符之间的空格

### How important is this to you?

Nice-to-have

### Describe the solution you'd like

replace "\s" with "" exclude "EOL"

### Describe alternatives you've considered

replace "\s" with "" exclude "EOL"

**Comment by wherewhere** [comment]
你无法确定是真的有空格还是假的有空格，所以不考虑。。。

**Comment by MineClever** [comment]
QAQ
